---
title: "Week 3 Discussion File"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Part A: Make edits (no conflict)

```{r partner_1a}
# Partner 1: 
# Run the code below to see the original graph
# Change the code below to make the point color change based on 'cut', and update the theme to theme_bw(). Update the title to include your first name. 

ggplot(data = diamonds, aes(x = carat, y = price)) +
  geom_point(aes(color = cut)) +
  theme_bw() +
  labs(title = "Rachel was here")
```

```{r partner_2a}
# Partner 2: 
# Run the code below to see the original graph
# Change the code below to make the geom a geom_jitter, and update the theme to theme_light. Update the title to include your first name. 

ggplot(data = diamonds, aes(x = color, y = carat)) +
  geom_jitter() +
  theme_light() +
  labs(title = "Roupen was here")
```

## PART B: Make problems

```{r break-it-1}


# A histogram!
ggplot(data = diamonds, aes(x = depth)) +
  geom_histogram(bins = 20, col = "black",
  fill = "dodgerblue") +
  theme_bw()

# Great plot by Rachel
ggplot(data = diamonds, aes(x = depth, y = cut)) +
  geom_col(aes(fill = cut)) +
  theme_minimal()

```

```{r break-it-2}
# things are getting crazy by Rachel - the most unhelpful graph ever....

ggplot(data = diamonds, aes(x = clarity, y = price)) +
  geom_point(aes(fill = cut)) +
  theme_dark()

# random math

2^2 + sqrt(6) - exp(9)

```

## END Discussion 3
